//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwaggerClientTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AssetDatabasesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssetDatabasesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwaggerClientTests.AssetDatabasesResource", typeof(AssetDatabasesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://bshang-web2/piwebapi.
        /// </summary>
        internal static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGreen.
        /// </summary>
        internal static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PI BI Project Asset Model.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f1a3ed36-4b15-4cbf-8fb8-cb53f63911a3.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\bshang-pi1\NuGreen.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://bshang-web2/piwebapi/assetdatabases/D03lhdDwK3_kmigxzMW4fJTQNu2j8RVLv0yPuMtT9jkRowQlNIQU5HLVBJMVxOVUdSRUVO.
        /// </summary>
        internal static string Self {
            get {
                return ResourceManager.GetString("Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D03lhdDwK3_kmigxzMW4fJTQNu2j8RVLv0yPuMtT9jkRowQlNIQU5HLVBJMVxOVUdSRUVO.
        /// </summary>
        internal static string WebId {
            get {
                return ResourceManager.GetString("WebId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S03lhdDwK3_kmigxzMW4fJTQQlNIQU5HLVBJMQ.
        /// </summary>
        internal static string WebIdAssetServer {
            get {
                return ResourceManager.GetString("WebIdAssetServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D03lhdDwK3_kmigxzMW4fJTQ6pSAwfoa3ka2MUua4pIq3AQlNIQU5HLVBJMVxTV0FHR0VSQ1JFQVRFVEVTVFM.
        /// </summary>
        internal static string WebIdCreate {
            get {
                return ResourceManager.GetString("WebIdCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E03lhdDwK3_kmigxzMW4fJTQ4wyhURqH5RG5bKjgnz9MRQQlNIQU5HLVBJMVxTV0FHR0VSQ1JFQVRFVEVTVFNcRVZFTlRGUkFNRUVMRU1FTlQ.
        /// </summary>
        internal static string WebIdEventFrameElement {
            get {
                return ResourceManager.GetString("WebIdEventFrameElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D03lhdDwK3_kmigxzMW4fJTQG0TPaxqhRUOEjalPDLrHewQlNIQU5HLVBJMVxUT0VYUE9SVA.
        /// </summary>
        internal static string WebIdToExport {
            get {
                return ResourceManager.GetString("WebIdToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D03lhdDwK3_kmigxzMW4fJTQ7FEJOvt1R0Wz02xJo-ziTwQlNIQU5HLVBJMVxJTVBPUlRFRERBVEFCQVNF.
        /// </summary>
        internal static string WebIdToImport {
            get {
                return ResourceManager.GetString("WebIdToImport", resourceCulture);
            }
        }
    }
}
